apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.fullName }}
  labels:
    app: kube-demo
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
